name: SquidGame
version: '1.0-SNAPSHOT'
main: fr.salut.squidgame.SquidGame
api-version: '1.20'

depend:
  - Multiverse-Core

commands:
  movedetection:
    description: "Command for switch move detection"
  test:
    description: "Command for test"
  rblocktoggle:
    description: "Command to toggle rblocks"
  prv:
    description: Commande pour gérer les états PRV.
    usage: /prv <ON|OFF|STOP>
ltte:
  description: Commande pour gérer les états LTTE.
  usage: /ltte <ON|OFF|STOP|timer <score>|prob <score>>
  bap:
    description: Commande pour gérer les états BaP.
    usage: /bap <ON|OFF|STOP>
  lifemode:
    description: Commande pour gérer le mode de vie.
    usage: /lifemode <mode|lifenumber|player <revive|reset <number>>>
    tab-completer: fr.salut.squidgame.component.commands.LifeModeCommand
  carrousel:
    description: Compte les joueurs dans les salles du carrousel
    usage: /carrousel room
  setepreuve:
    description: Définit l'épreuve actuelle.
    usage: /setepreuve <nom_de_l_epreuve>
  getepreuve:
    description: Affiche l'épreuve actuelle.
    usage: /getepreuve
permissions:
  sqg.admins.commands.*:
    description: "Donne l'accès aux commandes d'administration"
    default: op