name: SquidGame
version: '1.0-SNAPSHOT'
main: fr.salut.squidgame.SquidGame
api-version: '1.20'
commands:
  movedetection:
    description: "Command for switch move detection"
  test:
    description: "Command for test"
  rblocktoggle:
    description: "Command to toggle rblocks"
  prv:
    description: Commande pour gérer les états PRV.
    usage: /prv <ON|OFF|STOP>
  ltte:
    description: Commande pour gérer les états LTTE.
    usage: /ltte <ON|OFF|STOP>
  bap:
    description: Commande pour gérer les états BaP.
    usage: /bap <ON|OFF|STOP>

permissions:
  sqg.admins.commands.*:
    description: "Donne l'accès aux commandes d'administration"
    default: op